name: Deploy Production (Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/halalina-frontend:prod .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/halalina-frontend:prod

  deploy:
    name: Pull and Run on VPS (Prod)
    runs-on: self-hosted
    needs: build

    steps:
      - name: Stop and Remove Old Container
        run: |
          docker stop halalina-frontend-prod || true
          docker rm halalina-frontend-prod || true

      - name: Pull Latest Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/halalina-frontend:prod

      - name: Run New Container
        run: |
          docker run -d \
            --name halalina-frontend-prod \
            -p 80:3000 \
            --restart unless-stopped \
            --env-file ~/halalina-web/.env.prod \
            ${{ secrets.DOCKERHUB_USERNAME }}/halalina-frontend:prod
